<?php
/**
 * Created by PhpStorm.
 * User: rom
 * Date: 10/19/17
 * Time: 11:57 AM
 */

namespace App\Controller;


use Cake\Event\Event;

class UsersController extends AppController
{

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow('add');
    }

    public function add()
    {
        $user = $this->Users->newEntity();

        if($this->request->is('post'))
        {
            $user->set('role', 'user');
            $user = $this->Users->patchEntity($user, $this->request->getData());
            if($this->Users->save($user))
            {
                $this->Flash->success(_('User has been saved'));
                return $this->redirect(['action' => 'login']);
            }
            $this->Flash->error(__('Unable to register the user'));
        }
        $this->set('user',$user);
    }

    public function login()
    {
        if($this->request->is('post'))
        {
            $user = $this->Auth->identify();
            if($user)
            {
                $this->Auth->setUser($user);
            }
            else
            {
                $this->Flash->error(__('Invalid username or password, try again'));
            }
        }
    }

    public function logout()
    {

        return $this->redirect($this->Auth->logout());

    }

}