<?php
/**
 * Created by PhpStorm.
 * User: rom
 * Date: 11/23/17
 * Time: 5:35 PM
 */

namespace App\Controller;


use Cake\Event\Event;

class WelcomesController extends AppController
{

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow('index');
    }

    public function index()
    {

    }

}